name: GitHub-CI

on: [ push ]

permissions:
  contents: write
  checks: write
  actions: write
  id-token: write
  pages: write

jobs:

  build-and-test-with-reports:
    runs-on: ubuntu-latest

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: https://lorbus.github.io/demo-ui

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action

      - name: Make the script file executable
        run: chmod +x install-chrome.sh

      - name: Run install chrome script
        run: ./install-chrome.sh

      - name: Run Unit Tests
        run: npm test

      - name: Unit Tests Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: unit-tests-report
          path: '**/coverage/junit.xml'
          reporter: java-junit

      # Install npm dependencies, cache them correctly and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
