name: GitHub-CI

on: [ push ]

permissions:
  contents: write
  checks: write
  actions: write

jobs:
  build-and-test-with-reports:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install and Build
        run: |
          npm install
          npm run build

      # Workflow dispatch event that pushes the current version to the release branch.
      # From here the secondary production deployment workflow will trigger to build the dependencies.
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: releases/v4
          folder: .
          clean: false
          single-commit: true

      - name: Make the script file executable
        run: chmod +x install-chrome.sh

      - name: Run install chrome script
        run: ./install-chrome.sh

      - name: Run Unit Tests
        run: npm test

      - name: Unit Tests Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: unit-tests-report
          path: '**/coverage/junit.xml'
          reporter: java-junit

      # Install npm dependencies, cache them correctly and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
